# NomadUI Slider Configuration
# Edit these values to fine-tune slider behavior

scroll:
  # Delay before unlocking cursor after scrolling stops (in milliseconds)
  unlock_delay_ms: 150
  
  # Scroll sensitivity multiplier (higher = more sensitive)
  sensitivity: 0.01
  
  # Cursor forcing throttling (in milliseconds, lower = more responsive)
  cursor_force_throttle_ms: 16
  
  # Enable aggressive cursor forcing during scroll
  aggressive_cursor_forcing: true

drag:
  # Cursor forcing throttling for drag (in milliseconds)
  cursor_force_throttle_ms: 8
  
  # Enable aggressive cursor forcing during drag
  aggressive_cursor_forcing: true

visual:
  # Animation duration for shrink effect (in milliseconds)
  shrink_animation_duration_ms: 100
  
  # Animation duration for color fade (in milliseconds)
  color_animation_duration_ms: 180
  
  # Shrink factor (0.0 = no shrink, 1.0 = full shrink)
  shrink_factor: 0.25
