name: Private Release (requires manual trigger)

on:
  workflow_dispatch:

jobs:
  build-and-sign:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup MSVC
        run: echo "Assumes self-hosted runner with signing tools and secrets available"
      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release --parallel
      - name: Code sign
        env:
          SIGNING_CERT_PATH: ${{ secrets.SIGNING_CERT_PATH }}
          SIGNING_CERT_PASSWORD: ${{ secrets.SIGNING_CERT_PASSWORD }}
        run: |
          echo "The actual signing commands should run on a secure runner with access to the signing certificate."
          echo "Use signtool or osslsigncode on Windows with the certificate loaded from a secure store."
