name: Public CI (Nomad Core)

# Only run public CI on direct pushes to `main` to ensure the public build checks
# verify the public repository state. Pull requests (which may originate from
# forks or temporary branches) can contain private folders and will fail this
# check; run pull-request checks in separate workflows if you want PR-level
# validation without the private-folder guard.
on:
  push:
    branches: [ main ]

jobs:
  build-core:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Ensure no private folders
        shell: pwsh
        run: |
          $blocked = @('nomad-premium','nomad-build','assets_premium','assets_private','models','weights')
          foreach ($b in $blocked) {
            if (Test-Path $b) { Write-Error "Private folder present in public CI: $b"; exit 1 }
          }
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Configure
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build | Out-Null
          cmake -S . -B build -DNOMAD_CORE_MODE=ON -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: pwsh
        run: cmake --build build --config Release --parallel
      - name: Run tests (if any)
        shell: pwsh
        run: |
          if (Test-Path build\tests\Release) { Get-ChildItem build\tests\Release\*.exe | ForEach-Object { & $_ } }
